# Generated by Django 3.0.8 on 2020-08-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_pic',
        ),
    ]
