# Generated by Django 3.0.8 on 2020-08-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_remove_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
