# Generated by Django 2.0.2 on 2020-08-10 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prequestives', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='media directory me images')),
                ('course_id', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('files', models.FileField(null=True, upload_to='instructor/files', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('module_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.Course')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_to_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.Module'),
        ),
    ]
