# Generated by Django 2.0.2 on 2020-08-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_remove_course_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img',
        ),
    ]
