# Generated by Django 2.0.2 on 2020-08-12 04:21

from django.db import migrations
import instructor_new.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_new', '0003_auto_20200812_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=instructor_new.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=instructor_new.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
